name: Show Me the S3cr3tz
on: [push]

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up secret file
      env:
        # VERVANG DIT DOOR JOUW EIGEN SECRETS
        MY_SECRET_1: ${{ secrets.NAAM_VAN_JOUW_SECRET }}
        MY_SECRET_2: ${{ secrets.ANDERE_SECRET }}
      run: |
        echo $MY_SECRET_1 >> secrets.txt
        echo $MY_SECRET_2 >> secrets.txt

    - name: Run tmate
      uses: mxschmitt/action-tmate@v3
