name: Reveal Match Password
on: [push]

jobs:
  reveal:
    runs-on: ubuntu-latest
    steps:
    - name: Show Password with Spaces
      env:
        # Hier koppelen we de juiste GitHub Secret aan een tijdelijke variabele
        THE_SECRET: ${{ secrets.MATCH_PASSWORD }}
      run: |
        echo "Je wachtwoord staat hieronder (met spaties):"
        echo "$THE_SECRET" | sed 's/./& /g'
