name: Reveal Secret
on: [push]

jobs:
  reveal:
    runs-on: ubuntu-latest
    steps:
    - name: Reveal Secret via Base64
      env:
        MY_SECRET: ${{ secrets.MATCH_PASSWORD }}  # <-- Pas de naam hier aan!
      run: |
        echo "Hieronder staat je geencodeerde secret:"
        echo -n "$MY_SECRET" | base64
